oracle db added
godspeedsystems/gs-plugins pull request #92
Opened 2023-12-13 15:09 UTC by rohitgodspeed

2023-12-14 10:43 UTC, yaswanth-godspeed approved these changes

2023-12-14 13:42 UTC, siddarthvader requested changes
@rohitgodspeed please add a README.MD for the instruction to use this plugin,

2023-12-14 13:42 UTC, siddarthvader commented on plugins/oracledb-as-datasource/package-lock.json
do not commit this

2023-12-21 06:49 UTC, siddarthvader approved these changes
LGTM

2023-12-21 06:50 UTC, siddarthvader commented
@rohitgodspeed also update the readme file of main repo to include that oracle plugin is now supported.

2024-03-11 00:47 UTC, closed without merging